name: uppgift_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/Markus-Gemstad/flutter_kurs

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0

